#!/usr/bin/env bash
### evo-cmn -- Common management
### Usage: evo cmn [<command>]
###
### Commands: cmn setting   SettingsRegistry
###           cmn encoder   InterstellarEncoderV4
###           cmn ownership ObjectOwnership
###           cmn location  TokenLocation
###           cmn tokenuse  TokenUse
###           cmn points    UserPoints
###
### Example:  evo cmn setting uintOf UINT_AUCTION_CUT
###           evo cmn encoder getObjectClass @land

set -e

case $1 in
  setting)
    evo cmn-setting "${@:2}"
  ;;
  encoder)
    evo cmn-encoder "${@:2}"
  ;;
  ownership)
    evo cmn-ownership "${@:2}"
  ;;
  location)
    evo cmn-location "${@:2}"
  ;;
  tokenuse)
    evo cmn-tokenuse "${@:2}"
  ;;
  points)
    evo cmn-points "${@:2}"
  ;;
  *) evo help cmn
esac
	
set -e
