#!/usr/bin/env bash
### evo-sts-apo -- Apostle Status Management
### Usage: evo sts apo
###
### Commands: cmn sts apo <id> Apostle object status
###
### Example:  evo sts apo

set -e

p() { printf "%-5s %-5s   %-5s %-5s\n" "$1" "$2" "$3" "$4"; }
p2() { printf "%-5s %-5s %-5s %-5s %-5s\n" "$1" "$2" "$3" "$4" "$5"; }

id=$(seth --to-word ${1?})
class=$(( 16#${id:16:2} ))
if test "$class" != 2; then
  echo "The token id is not apostle."
  exit 1;
fi
info=$(evo apo-bas info "$id")
genes=$(seth --to-uint256 $(echo $info | cut -d' ' -f 1))
talents=$(seth --to-uint256 $(echo $info | cut -d' ' -f 2))
strength=$(( 16#${talents:64:2} ))
agility=$(( 16#${talents:62:2} ))
intellect=$(( 16#${talents:60:2} ))
life=$(( 16#${talents:58:2} ))
hp=$(( 16#${talents:56:2} ))
mood=$(( 16#${talents:54:2} ))
finesse=$(( 16#${talents:52:2} ))
lucky=$(( 16#${talents:50:2} ))
potential=$(( 16#${talents:48:2} ))

prefer=$(( 16#${talents:44:4} ))

prefer_gold=$(( ($prefer & (3 << (2 * 0))) >> (2 * 0) ))
prefer_wood=$(( ($prefer & (3 << (2 * 1))) >> (2 * 1) ))
prefer_water=$(( ($prefer & (3 << (2 * 2))) >> (2 * 2) ))
prefer_fire=$(( ($prefer & (3 << (2 * 3))) >> (2 * 3) ))
prefer_sioo=$(( ($prefer & (3 << (2 * 4))) >> (2 * 4) ))

charm=$(( 16#${talents:42:2} ))

strength_add=$(( 16#${talents:32:2} ))
agility_add=$(( 16#${talents:30:2} ))
intellect_add=$(( 16#${talents:28:2} ))
life_add=$(( 16#${talents:26:2} ))
hp_add=$(( 16#${talents:24:2} ))
mood_add=$(( 16#${talents:22:2} ))
finesse_add=$(( 16#${talents:20:2} ))
lucky_add=$(( 16#${talents:18:2} ))
potential_add=$(( 16#${talents:16:2} ))
charm_add=$(( 16#${talents:14:2} ))

strength=$(($strength + $strength_add))
agility=$(($agility + $aligity_add))
intellect=$(($intellect + $intellect_add))
life=$(($life + $life_add))
hp=$(($hp + $hp_add))
mood=$(($mood + $mood_add))
finesse=$(($finesse + $finesse_add))
lucky=$(($lucky + $lucky_add))
potential=$(($potential + $potential_add))

echo "####### Talent ##########"
p "LIFE" "$(($life))($life_add)" "MOOD" "$(($mood))($mood_add)"
p "STR" "$(($strength))($strength_add)" "AGI" "$(($agility))($agility_add)"
p "DEX" "$(($finesse))($finesse_add)" "HP" "$(($hp))($hp_add)"
p "INT" "$(($intellect))($intellect_add)" "LUK" "$(($lucky))($lucky_add)"
p "POT" "$(($potential))($potential_add)" "CHA" "$(($charm))($charm_add)"

echo "####### Prefer ##########"
p2 "GOLD" "WOOD" "HOO" "FIRE" "SIOO" 
p2 "Lv.$prefer_gold" "Lv.$prefer_wood" "Lv.$prefer_water" "Lv.$prefer_fire" "Lv.$prefer_sioo"

basic=$(bc <<< "$strength * $agility * 1000000000000000000 / ((7 + $potential / 100) * $potential)")
p "basic" $(seth --to-fix 18 $basic) 
