#!/usr/bin/env bash
### evo-cmn-setting -- Common Setting management
### Usage: evo cmn-setting [<command>]
###
### Commands: ls                        List all settings
###           uintOf <id>               Get uint property of id 
###           addressOf <id>            Get address property of id
###           setUint <id> <uint>       Set uint property of id
###           setAddress <id> <address> Set address property of id
###
### Example:  evo cmn-setting uintOf UINT_AUCTION_CUT
###           evo cmn-setting setUint UINT_AUCTION_CUT 400

set -e

setting="${SETTINGSREGISTRY?}" 

case $1 in
  ls)
    evo cmn-setting-all
  ;;
  uintOf)
    sig="uintOf(bytes32)(uint256)"
    id=$(evo --to-id "${2?}")
    seth call "$setting" "$sig" "$id"   
  ;;
  addressOf)
    sig="addressOf(bytes32)(address)"
    id=$(evo --to-id "${2?}")
    seth call "$setting" "$sig" "$id"   
  ;;
  setUint)
    sig="setUintProperty(bytes32,uint)"
    id=$(evo --to-id "${2?}")
    seth send "$setting" "$sig" "$id" "${3?}"
  ;;
  setAddress)
    sig="setAddressProperty(bytes32,address)"
    id=$(evo --to-id "${2?}")
    seth send "$setting" "$sig" "$id" "${3?}"
  ;;
  *) evo help cmn-setting
esac
