#!/usr/bin/env bash
### evo-mkt-tk1 -- Market TakeBack Management
### Usage: evo mkt-tk1 [<command>]
###
### Commands: token                                     TokenAdd
###           sup                                       Supervisor
###           net                                       NetworkId
###           u2n    <user>                             UserToNonce
###           take   <nonce> <value> <hash> <v> <r> <s> TakeBack
###           verify <hash>  <v>     <r>    <s>         Verify
###           setSup <sup>                              ChangeSupervisor
###
### Example:  evo mkt-tk1 settle 

set -e

tk1="${TAKEBACK_RING?}" 

case $1 in
  token)
    sig="tokenAdd()(address)"
    seth call "$tk1" "$sig"
  ;;
  sup)
    sig="supervisor()(address)"
    seth call "$tk1" "$sig"
  ;;
  net)
    sig="networkId()(uint256)"
    seth call "$tk1" "$sig"
  ;;
  u2n)
    sig="userToNonce(address)(uint256)"
    seth call "$tk1" "$sig" "${2?}"
  ;;
  verify)
    sig="verify(bytes32,uint8,bytes32,bytes32)(address)"
    seth call "$tk1" "$sig" "${@:2}"
  ;;
  take)
    sig="takeBack(uint256,uint256,bytes32,uint8,bytes32,bytes32)"
    seth send "$tk1" "$sig" "${@:2}"
  ;;
  setSup)
    sig="changeSupervisor(address)"
    seth send "$tk1" "$sig" "${@:2}"
  ;;
  *) evo help mkt-tk1
esac
