#!/usr/bin/env bash
### evo-sts -- Object Status Management
### Usage: evo sts [<command>]
###
### Commands: cmn sts lnd <id> Land object status
###           cmn sts apo <id> Apostle object status
###
### Example:  evo sts lnd @id

set -e

case $1 in
  lnd)
    evo sts-lnd "${@:2}"
  ;;
  apo)
    evo sts-apo "${@:2}"
  ;;
  *) evo help obj
esac
	
set -e
