#!/usr/bin/env bash
### evo-cmn -- Common management
### Usage: evo cmn [<command>]
###
### Commands: cmn reg regsRegistry
###           cmn enc InterstellarencV4
###           cmn tkn ObjectOwnership
###           cmn loc TokenLocation
###           cmn use TokenUse
###           cmn pts UserPoints
###
### Example:  evo cmn reg uintOf UINT_AUCTION_CUT
###           evo cmn enc getObjectClass @land

set -e

case $1 in
  reg)
    evo cmn-reg "${@:2}"
  ;;
  enc)
    evo cmn-enc "${@:2}"
  ;;
  tkn)
    evo cmn-tkn "${@:2}"
  ;;
  loc)
    evo cmn-loc "${@:2}"
  ;;
  use)
    evo cmn-use "${@:2}"
  ;;
  pts)
    evo cmn-pts "${@:2}"
  ;;
  *) evo help cmn
esac
	
set -e
