#!/usr/bin/env bash
### evo-cmn-location -- Common Ownership management
### Usage: evo cmn-location [<command>]
###
### Commands: has   <token-id>         HasLocation
###           getHM <token-id>         GetTokenLocationHM
###           setHM <token-id> <x> <y> SetTokenLocationHM
###           get   <token-id>         GetTokenLocation
###           set   <token-id> <x> <y> SetTokenLocation
###
### Example:  evo cmn-location balance @me
###           evo cmn-location owner @land

set -e

location="$(evo --addr-of "CONTRACT_TOKEN_LOCATION")" 

p() { printf "%-s %-52s \n" "$1" "$2"; }

case $1 in
  has)
    sig="hasLocation(uint256)(bool)"
    seth call "$location" "$sig" "${2?}"
  ;;
  getHM)
    sig="getTokenLocationHM(uint256)(int,int)"
    loc=$(seth call "$location" "$sig" "${2?}")
    x=$(echo $loc | cut -d' ' -f 1)
    y=$(echo $loc | cut -d' ' -f 2)
    p "x" "$x"
    p "y" "$x"
  ;;
  setHM)
    sig="setTokenLocationHM(uint256,int,int)"
    seth send "$location" "$sig" "${@:2}"
  ;;
  get)
    sig="getTokenLocation(uint256)(int,int)"
    loc=$(seth call "$location" "$sig" "${2?}")
    x=$(echo $loc | cut -d' ' -f 1)
    y=$(echo $loc | cut -d' ' -f 2)
    p "x" "$x"
    p "y" "$x"
  ;;
  set)
    sig="setTokenLocation(uint256,int,int)"
    seth send "$location" "$sig" "${@:2}"
  ;;
  *) evo help cmn-location
esac
