#!/usr/bin/env bash
### evo-cmn-points -- Common Ownership management
### Usage: evo cmn-points [<command>]
###
### Commands: balance <user>         PointsBalanceOf
###           supply                 PointsSupply
###
### Example:  evo cmn-points balance @me
###           evo cmn-points supply

set -e

points="$(evo --addr-of "CONTRACT_USER_POINTS")" 

case $1 in
  balance)
    sig="points(address)(uint256)"
    seth --to-fix 18 $(seth call "$points" "$sig" "${2?}")
  ;;
  supply)
    sig="pointsSupply()(uint256)"
    seth --to-fix 18 $(seth call "$points" "$sig" "${2?}")
  ;;
  *) evo help cmn-points
esac
