#!/usr/bin/env bash
### evo-lnd-bas -- Land Base Management
### Usage: evo lnd-bas [<command>]
###
### Commands: xLow                                                 Range x-low 
###           xHigh                                                Range x-high
###           yLow                                                 Range y-low
###           yHigh                                                Range y-high
###           r2a     <res-addr>                                   ResourceToken2RateAttrId
###           i2a     <token-id>                                   TokenId2LandAttr
###           l2i     <loc-id>                                     LocationId2TokenId
###           oid                                                  LastLandObjectId
###           new     <x>        <y>        <bene> <rate> <mask>   AssignNewLand
###           mnew    <x[]>      <y[]>      <bene> <rate> <mask[]> AssignMultipleLands
###           dr2a    <res-addr> <attr-id>                         DefineResouceTokenRateAttrId
###           loc     <x>        <y>                               GetTokenIdByLocation
###           exs     <x>        <y>                               Exists
###           owner   <x>        <y>                               OwnerOfLand
###           owners  <x[]>      <y[]>                             OwnerOfLandMany
###           land    <holder>                                     LandOf
###           box     <token-id>                                   IsHasBox
###           rsv     <token-id>                                   IsReserved
###           spc     <token-id>                                   IsSpecial
###           setBox  <token-id> <bool>                            SetHasBox
###           rra     <token-id>                                   GetResourceRateAttr
###           setRRA  <token-id> <attr-id>                         SetResourceRateAttr
###           mask    <token-id>                                   GetFlagMask
###           setMask <token-id> <mask>                            SetFlagMask
###           rate    <token-id> <res-addr>                        GetResourceRate
###           setRate <token-id> <res-addr> <rate>                 SetResourceRate
###
### Example:  evo lnd bas i2a @land 
###           evo lnd res mine

set -e

bas="$(evo --addr-of "CONTRACT_LAND_BASE")" 

p() { printf "%-8s %-9s %-15s\n" "$1" "$2" "$3"; }

case $1 in
  xLow)
    sig="xLow()(int256)"
    seth call "$bas" "$sig" 
  ;;
  xHigh)
    sig="xHigh()(int256)"
    seth call "$bas" "$sig" 
  ;;
  yLow)
    sig="yLow()(int256)"
    seth call "$bas" "$sig" 
  ;;
  yHigh)
    sig="yHigh()(int256)"
    seth call "$bas" "$sig" 
  ;;
  r2a)
    sig="resourceToken2RateAttrId(address)(int8)"
    seth call "$bas" "$sig" "${2?}"
  ;;
  i2a)
    sig="tokenId2LandAttr(uint256)(uint256,uint256)"
    attr=$(seth call "$bas" "$sig" "${2?}")
    resourceRateAttr=$(echo $attr | cut -d' ' -f 1)
    mask=$(echo $attr | cut -d' ' -f 2)
    p "resourceRateAttr" "$resourceRateAttr" 
    p "mask" "$mask"
  ;;
  l2i)
    sig="locationId2TokenId(uint256)(uint256)"
    seth call "$bas" "$sig" "${2?}"
  ;;
  oid)
    sig="lastLandObjectId()(uint256)"
    seth call "$bas" "$sig" 
  ;;
  new)
    sig="assignNewLand(int,int,address,uint256,uint256)"
    seth send "$bas" "$sig" "${@:2}"
  ;;
  mnew)
    sig="assignNewLand(int[],int[],address,uint256,uint256[])"
    seth send "$bas" "$sig" "${@:2}"
  ;;
  dr2a)
    sig="defineResouceTokenRateAttrId(address,uint8)"
    seth send "$bas" "$sig" "${@:2}"
  ;;
  loc)
    sig="getTokenIdByLocation(int,int)(uint256)"
    seth call "$bas" "$sig" "${@:2}"
  ;;
  exs)
    sig="exists(int,int)(bool)"
    seth call "$bas" "$sig" "${@:2}"
  ;;
  owner)
    sig="ownerOfLand(int,int)(address)"
    seth call "$bas" "$sig" "${@:2}"
  ;;
  owners)
    sig="ownerOfLand(int[],int[])(address[])"
    seth call "$bas" "$sig" "${@:2}"
  ;;
  land)
    sig="landOf(address)(int[],int[])"
    seth call "$bas" "$sig" "${@:2}"
  ;;
  box)
    sig="isHasBox(uint256)(bool)"
    seth call "$bas" "$sig" "${@:2}"
  ;;
  rsv)
    sig="isReserved(uint256)(bool)"
    seth call "$bas" "$sig" "${@:2}"
  ;;
  spc)
    sig="isSpecial(uint256)(bool)"
    seth call "$bas" "$sig" "${@:2}"
  ;;
  setBox)
    sig="setHasBox(uint,bool)"
    seth send "$bas" "$sig" "${@:2}"
  ;;
  rate)
    sig="getResourceRate(uint,address)(uint16)"
    seth call "$bas" "$sig" "${@:2}"
  ;;
  rra)
    sig="getResourceRateAttr(uint256)"
    attr=$(seth call "$bas" "$sig" "$2")
    startTime=$(evo lnd-res time)
    currentTime=$(date '+%s')
    num=$(((currentTime - startTime) / 86400))
    p "Resource" "Start" "Current"
    gold_rate=$(seth --to-dec ${attr:62:4})
    gold_crate=$(bc <<< "$gold_rate - $gold_rate * 0.0001 * $num")
    p "gold"   "$gold_rate" "$gold_crate"
    wood_rate=$(seth --to-dec ${attr:58:4})
    wood_crate=$(bc <<< "$wood_rate - $wood_rate * 0.0001 * $num")
    p "wood"   "$wood_rate" "$wood_crate"
    water_rate=$(seth --to-dec ${attr:54:4})
    water_crate=$(bc <<< "$water_rate - $water_rate * 0.0001 * $num")
    p "water" "$water_rate" "$water_crate"
    fire_rate=$(seth --to-dec ${attr:50:4})
    fire_crate=$(bc <<< "$fire_rate - $fire_rate * 0.0001 * $num")
    p "fire"   "$fire_rate" "$fire_crate"
    soil_rate=$(seth --to-dec ${attr:46:4})
    soil_crate=$(bc <<< "$soil_rate - $soil_rate * 0.0001 * $num")
    p "soil"   "$soil_rate" "$soil_crate"
    total=$(($gold_rate + $wood_rate + $water_rate + $fire_rate + $soil_rate))
    echo --------------------------------
    p "LEVEL" "$(($total/60 + $total/100))" 
  ;;
  mask)
    sig="getFlagMask(uint)(uint)"
    seth call "$bas" "$sig" "$2"
  ;;
  setRate)
    sig="setResourceRate(uint,address,uint16)"
    seth send "$bas" "$sig" "${@:2}"
  ;;
  *) evo help land-bas 
esac
	
set -e
