#!/usr/bin/env bash

set -eo pipefail

if  [[ -e .env ]]; then
    . .env
fi

GREEN='\033[0;32m'
NC='\033[0m' # No Color

log() {
    printf '%b\n' "${GREEN}${1}${NC}"
}

toUpper() {
    echo "$1" | tr '[:lower:]' '[:upper:]'
}

toLower() {
    echo "$1" | tr '[:upper:]' '[:lower:]'
}


addAddress() {
    if [ -z "$1" ] || [ -z "$2" ] || [ -z "$3" ]
      then
        echo "addAddress: No argument supplied"
        exit 1
    fi
    cat "$1" | jq --arg key "$2" --arg value "$3" '.[$key] = $value' | sponge "$1"
    # log "$2=$3"
}
